kind: Deployment
apiVersion: apps/v1
metadata:
  name: cm-env-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      type: cmapp1
  template:
    metadata:
      labels:
        type: cmapp1
    spec:
      containers:
       - name: cont1
         image: tomcat
         ports:
           - name: http
             containerPort: 8080
         envFrom:
          - configMapRef:
              name: con-map-cka