kind: Deployment
apiVersion: apps/v1
metadata:
  name: pv-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      type: pvapp
  template:
    metadata:
      labels:
        type: pvapp
    spec:
      volumes:
        - name: pvvol
          persistentVolumeClaim:
            claimName: my-pvc
      containers:
        - name: cont1
          image: tomcat
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: pvvol
              mountPath: /insdiecont-pvdata