kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-pvc
  labels:
    type: local
spec:
  volumeName: my-pv   ## must be the pv name that you want to claim
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce