services: 
  
  vote: 
    image: voting-app
    ports: 
      - 5000:80
    links: 
      - redis

  redis: 
    - image: redis

  worker: 
    image: worker-app
    links:
      - db
      - redis


  db:
    image: postgres:9.4
    environment: 
      POSTGRES_PASSWORD: "postgres"


  result: 
    image: result-app
    ports:
      - 5001:80 
    links: 
      - db