---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: litecoin
spec:
  selector:
    matchLabels:
      app: litecoin
  serviceName: "litecoin"
  replicas: 2
  template:
    metadata:
      labels:
        app: litecoin
    spec:
      containers:
      - name: shard
        image: charan19/docker-litecoin:latest
        ports:
        - containerPort: 9876
          name: litecoin-port
        env:
        - name: LITECOIN_VERSION
          value: 0.18.1
        readinessProbe:
          tcpSocket:
            port: 9333
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 9333
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: litecoin-pv
          mountPath: "/opt/litecoin"
  volumeClaimTemplates:
  - metadata:
      name: litecoin-pv
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: litecoin
  labels:
    app: litecoin
spec:
  ports:
  - port: 9876
  clusterIP: None
  selector:
    app: litecoin
---
kind: StorageClass
metadata:
  name: litecoin
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "10"
  fsType: ext4