kind: Deployment 
apiVersion: apps/v1
metadata:
  name: deployment1
  # labels:   not mandatory 
spec:
  replicas: 10
  minReadySeconds: 45
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector: 
    matchLabels: 
      role: app
  template:   # pod template which need to be created, which include always about the pod metadata & spec
    metadata:
      #name: test
      labels: 
        role: app
    spec:
      containers:
        - name: cont1
          image: nginx:1.18
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443 

              